spring:
  application:
    name: chat

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 数据库连接池
  datasource:
    druid:
      # 数据库连接
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.56.104:3306/chat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
      # 更改密码
      username: mrying
      password: 123456

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB

  redis:
    port: 6379
    host: 192.168.56.104

# 端口号
server:
  port: 8081
  servlet:
    context-path: /api
    encoding:
      enabled: true
      charset: UTF-8
      force: true

# 设置 MyBatis
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

api:
  chatgpt:
    host: https://api.chatanywhere.com.cn/
    gptKey: sk-BVS6lkw0gCx6iA3PMwxXWKMBPqZy46K4bHbaHgqzc7KwEZse

# JWT 配置
jwt:
  data:
    # jwt加密密钥
    secret: 2bc1a2207c684d7fb29df11f8abdc815
    # jwt的过期时间(60s*60min*24h*7day)
    expiration: 604800